services:
  toolbox-api:
    image: toolbox-api:latest
    container_name: toolbox-api
    ports:
      - "4005:4005"
    restart: always
    logging:
      driver: "json-file"
      options:
        max-size: "20m"
        max-file: "5"
    volumes:
      - ./toolbox_data:/app/toolbox_data
    environment:
      - GIN_MODE=release 
    networks:
      - proxy_net

networks:
  proxy_net:
    external: true
    name: api-proxy_proxy_net